services:
  tModLoader:
    build: .
    image: guillheu/tmodloader-dedicated-server
    volumes:
      - ./Mods:/root/terraria-server/workshop-mods/steamapps/workshop
      - ./Worlds:/root/.local/share/Terraria/tModLoader/Worlds
      - ./serverconfig.txt:/root/terraria-server/serverconfig.txt
      - ./install.txt:/root/terraria-server/install.txt
      - ./entrypoint.sh:/root/terraria-server/entrypoint.sh
      - ./enabled.json:/root/.local/share/Terraria/tModLoader/Mods/enabled.json
      - ./log.txt:/root/terraria-server/log.txt
    ports:
      - "7777:7777"
    restart: always